version: "3"

services:
  micronaut:
    image: com.crappyengineering.micronaut/micronaut-demo
#    build:
#      context: micronaut-demo/
#      dockerfile: Dockerfile
    ports:
    - 7000:8080

  spring:
    image: com.crappyengineering.springboot/springboot-demo
    ports:
      - 8000:8080

  dropwizard:
    build:
      context: dropwizard-demo/
      dockerfile: Dockerfile
    ports:
      - 9000:8080

  db:
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
    - 6000:5432

  swagger:
    image: com.crappyengineering.micronaut/swagger-server
    ports:
      - 7100:8080