version: "3.7"

services:
  task:
    depends_on:
      - db
    image: 'no.knowit.jvm.chapter/micronaut-task'
    ports:
      - 7001:8080
    environment:
      - CONSUL_HOST=consul

  tasklist:
    depends_on:
    - db
    image: 'no.knowit.jvm.chapter/micronaut-tasklist'
    ports:
      - 8001:8080
    environment:
      - CONSUL_HOST=consul

  consul:
    image: consul
    ports:
      - 8500:8500

  db:
    depends_on:
      - consul
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
    - 6001:5432
